---
- name: Gather information from hosts
  hosts: 192.168.56.8
  gather_facts: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3  
  tasks:
    - name: Get hostname
      set_fact:
        hostname: "{{ inventory_hostname }}"
