---
- name: Master playbook
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3  
  tasks:
    - name: Run gather_info playbook
      include_tasks: hierarchy_test.yml
 
    - name: Run use_info playbook
      include_tasks: use_info.yml
